name: Automatic Deployment

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
        run: echo Start deploying SenReg
      - name: Checkout git
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test
